server:
  port: ${PORT:8769}
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hejiajie6318272/config_properties.git
          username: hejiajie6318272
          password: hejiajie5050
          searchPaths: config_properties
      label: master
  application:
    name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://eureka01:8001/eureka/

