server:
  port: ${PORT:8006}
eureka:
  instance:
    hostname: eureka-client
  client:
    serviceUrl: 
      defaultZone: http://eureka01:8001/eureka/
spring:
  application:
    name: eureka-client
    

